# Generated by Django 6.0.4 on 2026-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("visa", "VISA"),
                            ("humo", "HUMO"),
                            ("uzcard", "UZCARD"),
                            ("naqd", "NAQD"),
                        ],
                        max_length=20,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=16)),
                ("card_number", models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
