# Generated by Django 6.0.4 on 2026-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[("uzs", "UZS"), ("usd", "USD")], default="uzs", max_length=30
            ),
        ),
    ]
