# Generated by Django 6.0.4 on 2026-04-23 22:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="card_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Karta raqami aynan 16 ta raqamdan iborat bo'lishi shart!",
                        regex="^\\d{16}$",
                    )
                ],
            ),
        ),
    ]
