# Generated by Django 6.0.4 on 2026-04-26 11:32

import creditcards.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="card_number",
            field=creditcards.models.CardNumberField(
                blank=True,
                help_text="16 xonali karta raqamini kiriting",
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)),
                name="balance_negative_bolmasin",
            ),
        ),
    ]
