# Generated by Django 6.0.4 on 2026-04-26 14:12

import creditcards.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_card_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="card_number",
            field=creditcards.models.CardNumberField(
                default=django.utils.timezone.now,
                help_text="16 xonali karta raqamini kiriting",
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[("visa", "VISA"), ("humo", "HUMO"), ("uzcard", "UZCARD")],
                max_length=20,
            ),
        ),
    ]
