# Generated by Django 6.0.4 on 2026-04-26 14:19

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_account_card_number_alter_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="card_number",
            field=creditcards.models.CardNumberField(
                help_text="16 xonali karta raqamini kiriting",
                max_length=25,
                unique=True,
            ),
        ),
    ]
