# Generated by Django 6.0.4 on 2026-04-23 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="from_account",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="to_account",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="user",
        ),
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
        migrations.AddField(
            model_name="transaction",
            name="comment",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="Transfer",
        ),
    ]
