# Generated by Django 6.0.4 on 2026-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_category_user_alter_transaction_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
