# Generated by Django 6.0.4 on 2026-04-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_transaction_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="limit",
        ),
    ]
